name: Docker Image build and push

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build Docker image backend
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: api/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/time-backend:latest

    - name: Build Docker image frontend
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/time-frontend:latest



