name: Docker Image build and push

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build Docker image backend
      run: docker build . --file api/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/time-app

    - name: Build Docker image frontend
      run:  docker build . --file frontend/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/time-app

    - name: Publish  images to Dockerhub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/time-app:latest



