name: Docker Image build and push

on:
  push:
    branches: [ "master" ]

jobs:

  build-time:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build Docker image frontend
      run: docker build . --file frontend/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/ftime

    - name: Publish frontend image to Dockerhub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/time-front:latest

    - name: Build Docker image backend
      run: docker build . --file api/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/btime

    - name: Publish backend image to Dockerhub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/time-backend:latest




